# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChartsSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChartsSample
  
  pod 'Charts' #, :git => 'https://github.com/danielgindi/Charts.git', :branch => 'master'

  target 'ChartsSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChartsSampleUITests' do
    # Pods for testing
  end

end
